language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - timeout 60 npm run build
  - npm test
  - npm run justdoit -- --repo https://$GH_TOKEN@github.com/k1sul1/wp-plugin.pro.git
